# Generated by Django 3.2.10 on 2022-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='first_user_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='second_user_seen',
            field=models.BooleanField(default=True),
        ),
    ]
