# Generated by Django 3.2.10 on 2022-02-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_skill_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='userprofile.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='userprofile.profile'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='userprofile.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='userprofile.profile'),
        ),
    ]
