# Generated by Django 3.2.10 on 2022-03-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20220227_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_profile',
            field=models.ManyToManyField(blank=True, related_name='skills', to='userprofile.Profile'),
        ),
    ]
