# Generated by Django 3.2.10 on 2022-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20220402_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='userprofile.Skill'),
        ),
    ]
