# Generated by Django 3.2.10 on 2022-02-14 05:48

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/user/default.png', upload_to=userprofile.models.create_path_images),
        ),
    ]
