# Generated by Django 3.2.10 on 2022-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20220215_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
