# Generated by Django 3.2.10 on 2022-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20220221_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
